changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
  categories:
    - title: Breaking changes
      labels: [breaking-change]
    - title: Features
      labels: [enhancement, feature]
    - title: Fixes
      labels: [bug, fix]
    - title: Security
      labels: [security]
    - title: Documentation and operations
      labels: [documentation, ci, containers]
    - title: Other changes
      labels: ["*"]
